# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DKVK' do

use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'ARSLineProgress'
  pod 'Locksmith'
end
